const damage = {
   "Clan Ship": {
      "Tap": 0,
      "Hero": 1,
      "All": 1,
      "Crit dmg": 1,
      "Base hero": 1,
      "Gunblade": 0,
      "Pet": 0,
      "CS": 1,
      "Dagger": 0,
      "Gold Gun": 0,
      "HS": 0,
      "DS": 0.5,
      "FS": 0,
      "WC": 1,
      "SC": 0,
      "Dual Pet": 0,
      "Thunder Ship": 1,
      "Dagger Stream": 0,
      "Twilight Fairy": 0,
      "Sword": 1,
      "Helmet": 1,
      "Aura": 1,
      "Slash": 1,
      "Crit Chance": 0.5,
      "Dimensional Shift": 2.5,
      "Tactical Insight": 107,
      "Companion Warfare": 4,
      "Tap from Heroes": 0,
      "Companion": 1,
      "All Prob": 1
   },
   "Shadow Clone": {
      "Tap": 0.6,
      "Hero": 0.6,
      "All": 1,
      "Crit dmg": 1,
      "Base hero": 1,
      "Gunblade": 0.6,
      "Pet": 0,
      "CS": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "HS": 0,
      "DS": 0.6,
      "FS": 0.6,
      "WC": 0.6,
      "SC": 1,
      "Dual Pet": 0,
      "Thunder Ship": 0,
      "Dagger Stream": 0,
      "Twilight Fairy": 1,
      "Sword": 1,
      "Helmet": 0.6,
      "Aura": 1,
      "Slash": 1,
      "Crit Chance": 1.5,
      "Dimensional Shift": 3.8,
      "Tactical Insight": 108.6,
      "Companion Warfare": 3.6,
      "Tap from Heroes": 1,
      "Companion": 1,
      "All Prob": 2.1
   },
   "Heavenly Strike": {
      "Tap": 1,
      "Hero": 0.5,
      "All": 1,
      "Crit dmg": 1,
      "Base hero": 1,
      "Gunblade": 0.75,
      "Pet": 0,
      "CS": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "HS": 1,
      "DS": 0,
      "FS": 1,
      "WC": 0.5,
      "SC": 0,
      "Dual Pet": 0,
      "Thunder Ship": 0,
      "Dagger Stream": 0,
      "Twilight Fairy": 1,
      "Sword": 1,
      "Helmet": 0.75,
      "Aura": 1,
      "Slash": 1,
      "Crit Chance": 0,
      "Dimensional Shift": 3.5,
      "Tactical Insight": 111,
      "Companion Warfare": 3.75,
      "Tap from Heroes": 1,
      "Companion": 0,
      "All Prob": 0
   },
   "Pet": {
      "Tap": 1,
      "Hero": 0.5,
      "All": 1,
      "Crit dmg": 1,
      "Base hero": 1,
      "Gunblade": 0,
      "Pet": 1,
      "CS": 0,
      "Dagger": 0,
      "Gold Gun": 0,
      "HS": 0,
      "DS": 0.7,
      "FS": 1,
      "WC": 0.5,
      "SC": 0,
      "Dual Pet": 1,
      "Thunder Ship": 0,
      "Dagger Stream": 0,
      "Twilight Fairy": 0,
      "Sword": 1,
      "Helmet": 0.5,
      "Aura": 1,
      "Slash": 1,
      "Crit Chance": 1,
      "Dimensional Shift": 3.2,
      "Tactical Insight": 111,
      "Companion Warfare": 3.5,
      "Tap from Heroes": 1,
      "Companion": 1,
      "All Prob": 1.7
   },
   "Dagger": {
      "Tap": 1,
      "Hero": 0.5,
      "All": 1,
      "Crit dmg": 1,
      "Base hero": 1,
      "Gunblade": 0.65,
      "Pet": 0,
      "CS": 0,
      "Dagger": 1,
      "Gold Gun": 0,
      "HS": 0,
      "DS": 0.75,
      "FS": 1,
      "WC": 0.5,
      "SC": 0,
      "Dual Pet": 0,
      "Thunder Ship": 0,
      "Dagger Stream": 1,
      "Twilight Fairy": 0,
      "Sword": 1,
      "Helmet": 0.65,
      "Aura": 1,
      "Slash": 1,
      "Crit Chance": 1.5,
      "Dimensional Shift": 3.25,
      "Tactical Insight": 111,
      "Companion Warfare": 3.65,
      "Tap from Heroes": 1,
      "Companion": 0,
      "All Prob": 2.3
   },
   "Gold Gun": {
      "Tap": 0.45,
      "Hero": 0.9,
      "All": 1,
      "Crit dmg": 1,
      "Base hero": 1,
      "Gunblade": 0.75,
      "Pet": 0,
      "CS": 0,
      "Dagger": 0,
      "Gold Gun": 1,
      "HS": 0,
      "DS": 0.6,
      "FS": 0.45,
      "WC": 0.9,
      "SC": 0,
      "Dual Pet": 0,
      "Thunder Ship": 0,
      "Dagger Stream": 0,
      "Twilight Fairy": 0,
      "Sword": 1,
      "Helmet": 0.9,
      "Aura": 1,
      "Slash": 1,
      "Crit Chance": 1,
      "Dimensional Shift": 1.95,
      "Tactical Insight": 114.8,
      "Companion Warfare": 3.9,
      "Tap from Heroes": 1,
      "Companion": 0,
      "All Prob": 1.6
   }
};

const gold = {
   "Fairy": {
      "All": 1,
      "Chesterson": 1,
      "Jackpot": 1,
      "Boss": 0,
      "Fairy": 1,
      "HoG": 0,
      "HoM": 0.6,
      "Multi Titan": 0,
      "Specialty": 1,
      "Chesterson chance": 1,
      "Armor": 1,
      "Tactical Insight": 83,
      "Companion Warfare": 1
   },
   "Heart of Gold": {
      "All": 1,
      "Chesterson": 0,
      "Jackpot": 1,
      "Boss": 1,
      "Fairy": 0,
      "HoG": 1,
      "HoM": 0.6,
      "Multi Titan": 0,
      "Specialty": 1,
      "Chesterson chance": 0,
      "Armor": 1,
      "Tactical Insight": 79,
      "Companion Warfare": 1
   },
   "Chesterson": {
      "All": 1,
      "Chesterson": 1,
      "Jackpot": 1,
      "Boss": 0,
      "Fairy": 0,
      "HoG": 0,
      "HoM": 1,
      "Multi Titan": 1,
      "Specialty": 0,
      "Chesterson chance": 1,
      "Armor": 1,
      "Tactical Insight": 78,
      "Companion Warfare": 1
   }
}
